<?php
if(!defined('IN_DISCUZ')) {
	exit('Access Denied');
}

$plang['scriptlang'] = array(
	'fieldclass_num' => '数字',
	'fieldclass_text' => '单行文本',
	'fieldclass_textarea' => '多行文本',
	'fieldclass_select' => '下拉选择',
	'fieldclass_mselect' => '多行下拉',
	'fieldclass_radio' => '单选',
	'fieldclass_checkbox' => '复选',
	'fieldclass_image' => '图片',
	'fieldclass_ditu' => '地图',
	'fieldclass_time' => '时间',
	'fieldclass_date' => '日期',
	'maxnum' => '数值最大值(可选): ',
	'minnum' => '数值最小值(可选): ',
	'inputnum' => '表单显示长度(可选):',
	'defaultvalue' => '默认值(可选):',
	'maxtext' => '文本内容最大值(可选): ',
	'mintext' => '文本内容最小值(可选): ',
	'inputtext' => '表单显示长度(可选):',
	'delfield_success' => '字段删除成功',
	'addfield_success' => '新建字段成功',
	'editfield_success' => '字段编辑成功',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
);
$plang['templatelang'] = array(
	'zongfield' => '总字段数',
	'jszfield' => '驾驶证字段数',
	'chlfield' => '车辆信息字段数',
	'fieldtype' => '字段种类',
	'fieldlist' => '字段列表',
	'fieldedit' => '字段编辑',
	'fieldadd' => '新增字段',
	'fieldname' => '字段标识',
	'fieldtitle' => '字段名称',
	'fieldtips' => '注释',
	'fieldclass' => '字段类别',
	'fieldparameter' => '字段参数',
	'jszlist' => '驾驶证信息',
	'jszedit' => '编辑驾驶证',
	'chllist' => '车辆信息',
	'chledit' => '编辑车辆信息',
	'operate' => '操作',
	'edit' => '编辑',
	'delete' => '删除',
	'srch' => '搜索',
	'submit' => '确定',
	'displayorder' => '排序',
	'required' => '必填',
	'fieldtype_comment' => '选择字段类型',
	'fieldname_comment' => '字段的名称，用户数据表中的字段和变量名称，必须是英文',
	'fieldtitle_comment' => '字段的显示标称的名字',
	'fieldtips_comment' => '注释内容',
	'fieldclass_comment' => '选择字段的类别',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
);
$plang['installlang'] = array(
	'' => '',
);
$plang['systemlang'] = array(
	'file' => array(
		'' => '',
		),
	);
?>