<?php
if(!defined('IN_DISCUZ')) {
	exit('Access Denied');
}

$plang['scriptlang'] = array(
	'fieldclass_num' => '数字',
	'fieldclass_text' => '单行文本',
	'fieldclass_textarea' => '多行文本',
	'fieldclass_select' => '下拉选择',
	'fieldclass_mselect' => '多行下拉',
	'fieldclass_radio' => '单选',
	'fieldclass_checkbox' => '复选',
	'fieldclass_image' => '图片',
	'fieldclass_ditu' => '地图',
	'fieldclass_time' => '时间',
	'fieldclass_date' => '日期',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
);
$plang['templatelang'] = array(
	'zongfield' => '总字段数',
	'jszfield' => '驾驶证字段数',
	'chlfield' => '车辆信息字段数',
	'fieldtype' => '字段种类',
	'fieldlist' => '字段列表',
	'fieldedit' => '字段编辑',
	'fieldname' => '字段标识',
	'fieldtitle' => '字段名称',
	'fieldtips' => '注释',
	'fieldclass' => '字段类别',
	'fieldparameter' => '字段参数',
	'jszlist' => '驾驶证信息',
	'jszedit' => '编辑驾驶证',
	'chllist' => '车辆信息',
	'chledit' => '编辑车辆信息',
	'operate' => '操作',
	'edit' => '编辑',
	'delete' => '删除',
	'srch' => '搜索',
	'submit' => '确定',
	'displayorder' => '排序',
	'required' => '必填',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
);
$plang['installlang'] = array(
	'' => '',
);
$plang['systemlang'] = array(
	'file' => array(
		'' => '',
		),
	);
?>