<?php
if(!defined('IN_DISCUZ')) {
	exit('Access Denied');
}

$plang['scriptlang'] = array(
	'fieldclass_num' => '数字',
	'fieldclass_text' => '单行文本',
	'fieldclass_textarea' => '多行文本',
	'fieldclass_select' => '下拉选择',
	'fieldclass_mselect' => '多行下拉',
	'fieldclass_radio' => '单选',
	'fieldclass_checkbox' => '复选',
	'fieldclass_image' => '图片',
	'fieldclass_ditu' => '地图',
	'fieldclass_time' => '时间',
	'fieldclass_date' => '日期',
	'maxnum' => '数值最大值(可选): ',
	'minnum' => '数值最小值(可选): ',
	'inputnum' => '表单显示长度(可选):',
	'defaultvalue' => '默认值(可选):',
	'maxtext' => '文本内容最大值(可选): ',
	'mintext' => '文本内容最小值(可选): ',
	'inputtext' => '表单显示长度(可选):',
	'delfield_success' => '字段删除成功',
	'addfield_success' => '新建字段成功',
	'editfield_success' => '字段编辑成功',


	'cyhgroup_list_tips' => '车友会的会员组的编辑，在这里可以定制',
	'cyhgroup_list' => '会员组列表',
	'groupname' => '会员组名称',
	'add_group' => '增加会员组',
	'group_option' => '会员组选项',
	'add_group_tips' => '增加新的会员组',
	'edit_group_tips' => '编辑会员组',
	'groupstatus' => '会员组是否启用',
	'groupstatus_comment' => '选择会员组是否启用',
	'add' => '新建',
	'del' => '删除',
	'edit' => '编辑',
	'cha' => '搜索',
	'groupname_comment' => '填写用户组的名称',
	'groupquanxian' => '会员组权限',
	'qx_add' => '增',
	'qx_edit' => '改',
	'qx_del' => '删',
	'qx_cha' => '查',
	'edit_group_succeed' => '会员组编辑成功',
	'infolist' => '信息列表',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'add_info' => '增加新的信息',
	'add_infotype' => '新建新的信息分类',
	'infotypename' => '信息分类标识',
	'infotypetitle' => '信息分类名称',
	'edit_infotype_succeed' => '信息分类编辑成功',
	'infotype_list' => '信息分类列表',
	'infotype_list_tips' => '<li>信息分类标识必须是英文，因为要建立同名数据表；</li><li>信息分类的名称不要超过四个字</li>',
	'field_list_tips' => '信息的字段编辑',
	'select_infotype' => '选择信息分类',
	'infotype' => '信息分类',
	'fieldlist' => '字段列表',
	'edit_field_succeed' => '信息分类编辑成功',
	'edit_field_tips' => '对信息字段进行详细设置',
	'field_option' => '字段选项',
	'field_info' => '字段所属信息分类基本信息',
	'shengcheng' => '生成',
	'export' => '导出',
	'' => '',
	'' => '',
);
$plang['templatelang'] = array(
	'zongfield' => '总字段数',
	'jszfield' => '驾驶证字段数',
	'chlfield' => '车辆信息字段数',
	'fieldtype' => '字段种类',
	'fieldlist' => '字段列表',
	'fieldedit' => '字段编辑',
	'fieldadd' => '新增字段',
	'fieldname' => '字段标识',
	'fieldtitle' => '字段名称',
	'fieldtips' => '注释',
	'fieldclass' => '字段类别',
	'fieldparameter' => '字段参数',
	'jszlist' => '驾驶证信息',
	'jszedit' => '编辑驾驶证',
	'chllist' => '车辆信息',
	'chledit' => '编辑车辆信息',
	'operate' => '操作',
	'edit' => '编辑',
	'delete' => '删除',
	'srch' => '搜索',
	'submit' => '确定',
	'displayorder' => '排序',
	'required' => '必填',
	'fieldtype_comment' => '选择字段类型',
	'fieldname_comment' => '字段的名称，用户数据表中的字段和变量名称，必须是英文',
	'fieldtitle_comment' => '字段的显示标称的名字',
	'fieldtips_comment' => '注释内容',
	'fieldclass_comment' => '选择字段的类别',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
);
$plang['installlang'] = array(
	'' => '',
);
$plang['systemlang'] = array(
	'file' => array(
		'' => '',
		),
	);
?>