<?php
if(!defined('IN_DISCUZ')) {
	exit('Access Denied');
}

$plang['scriptlang'] = array(
	'menu_list' => '菜单列表',
	'sitegroup_option' => '站长组选项',
	'sitegroup_name' => '站长组名称',
	'sitegroup_name_comment' => '可以是中文，站长组的名称',
	'export' => '导出',
	'add_sitegroup' => '新建站长组',
	'add_sitegroup_tips' => '新建站长组注释',
	'sitegroup_admincp_access' => '站长组后台权限',
	'add_sitegroup_succeed' => '新建站长组成功',
	'edit_sitegroup_succeed' => '站长组修改成功',
	'menutype_admincp' => '后台菜单',
	'menutype_member' => '会员中心',
	'menutype_yiqixueba' => '前台页面',
	'menu_list_tips' => '菜单管理注释',
	'menu_name' => '菜单链接',
	'menu_title' => '菜单名称',
	'modfile' => '节点文件',
	'status' => '状态',
	'add_submenu' => '新建二级菜单',
	'add_menu' => '新建菜单',
	'menu_edit_succeed' => '菜单编辑成功',
	'server_mokuai_list_tips' => '模块设计注释',
	'server_mokuai_list' => '模块列表',
	'mokuai_name' => '模块名称',
	'mokuai_description' => '模块简述',
	'add_mokuai' => '增加模块',
	'version' => '版本',
	'pagelist' => '页面',
	'mokuaisetting' => '设置',
	'edit' => '编辑',
	'mokuai_make' => '生成',
	'price:' => '价格：',
	'version:' => '版本：',
	'rmb' => '元',
	'delete' => '删除',
	'displayorder' => '排序',
	'edit_mokuai_succeed' => '模块编辑成功',
	'mokuai_qiehuan_succeed' => '模块切换成功',
	'add_ver' => '新建版本',
	'add_mokuai' => '新建模块',
	'mokuai_biaoshi' => '模块标识',
	'mokuai_biaoshi_comment' => '必须是英文，在此处不能修改',
	'edit_mokuai_tips' => '模块编辑',
	'mokuai_option' => '模块选项',
	'mokuai_version' => '模块版本',
	'mokuai_version_comment' => '不用加V',
	'mokuai_name_comment' => '模块名称，可以是中文',
	'mokuai_price' => '模块价格',
	'mokuai_price_comment' => '请填写模块的价格',
	'mokuai_description_comment' => '模块的简单描述',
	'mokuai_ico' => '模块图标',
	'mokuai_ico_comment' => '与DISCUZ的插件的图片大规格一致',
	'mokuaiinformation' => '模块详细描述',
	'mokuai_newtag' => '新建标签',
	'mokuai_newtag_comment' => '如果上边的标签中没有的话，可以添加，多个用半角的,分割',
	'mokuai_tag' => '模块搜索、分类标签',
	'sitegroup_list_tips' => '站长组注释',
	'sitegroup_list' => '站长组列表',
	'mokuainode' => '节点',
	'mokuai_node_tips' => '模块节点编辑注释',
	'mokuai_node' => '节点列表',
	'nodetype' => '节点类型',
	'node_admincp' => '后台节点',
	'node_member' => '会员中心',
	'node_yiqixueba' => '前台页面',
	'node_api' => 'API节点',
	'node_ajax' => 'AJAX节点',
	'node_hook' => '插件钩子',
	'node_name' => '标识',
	'add_node' => '新建节点',
	'node_title' => '节点名称',
	'edit_node_succeed' => '节点编辑成功',
	'node_menu' => '菜单显示',
	'node_menu_order' => '显示顺序',
	'current_mokuai' => '当前模块',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
	'' => '',
);
$plang['templatelang'] = array(
	'' => '',
);
$plang['installlang'] = array(
	'' => '',
);
$plang['systemlang'] = array(
	'file' => array(
		'' => '',
		),
	);
?>